FROM arm64v8/node
EXPOSE 3000
ENTRYPOINT ["node"]
CMD ["server"]

HEALTHCHECK --start-period=5s \
        CMD curl --fail localhost:3000/api/v1/health || exit 1

# Install dependencies
RUN apt update && \
    apt upgrade -y

# Create app directory
RUN mkdir -p /app/dist
WORKDIR /app

# Install app dependencies
COPY package.json \
     package-lock.json \
     /app/

RUN npm install

# Bundle app source
COPY dist/favicon* /app/dist/
COPY migrations /app/migrations
COPY plugins /app/plugins
COPY lib /app/lib
COPY api /app/api
COPY webapp /app/webapp
COPY test /app/test
COPY server.js \
     door.js \
     webpack.config.js \
     .eslintrc.json \
     /app/

# Build
RUN node_modules/.bin/webpack
