FROM arm32v8/node
EXPOSE 3000
ENTRYPOINT ["node"]
CMD ["server"]

# Install dependencies
RUN apt update && \
    apt upgrade

# Create app directory
RUN mkdir -p /usr/src/app/dist
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
COPY package-lock.json /usr/src/app/
RUN npm install --only=production

# Bundle app source
COPY migrations /usr/src/app/migrations
COPY server.js /usr/src/app/
COPY door.js /usr/src/app/
COPY lib /usr/src/app/lib
COPY api /usr/src/app/api
COPY dist/index.html dist/favicon* /usr/src/app/dist/
COPY webpack.config.js /usr/src/app/
COPY webapp /usr/src/app/webapp

# Build
RUN node_modules/.bin/webpack

