FROM resin/armv7hf-debian AS base
EXPOSE 3000
ENTRYPOINT ["node"]
CMD ["server"]

RUN [ "cross-build-start" ]

# Create app directory
RUN mkdir -p /usr/src/app/dist
WORKDIR /usr/src/app

# Install updates
RUN curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
RUN apt update && \
    apt upgrade && \
    apt install nodejs

# Install build dependencies
FROM base AS build
RUN apt install git python make g++

# Install app dependencies
COPY package.json /usr/src/app/
COPY package-lock.json /usr/src/app/
RUN npm install --only=production && npm cache clean --force && rm -rf /tmp/*

# Make app
FROM base
COPY --from=build /usr/src/app/node_modules /usr/src/app/node_modules

# Bundle app source
COPY migrations /usr/src/app/migrations
COPY server.js /usr/src/app/
COPY door.js /usr/src/app/
COPY lib /usr/src/app/lib
COPY api /usr/src/app/api
COPY dist/index.html /usr/src/app/dist
COPY webpack.config.js /usr/src/app/
COPY webapp /usr/src/app/webapp

# Build webapp
RUN node_modules/.bin/webpack

RUN [ "cross-build-end" ]

